### ISSUE TITLE
*** No rule to make target `glusterrest.py', needed by `install-restapiPYTHON'.  Stop.

### ISSUE THREAD

**Issue by du2016** [gluster/restapi#3]
*** No rule to make target `glusterrest.py', needed by `install-restapiPYTHON'.  Stop.

**Comment by du2016** [comment]
when run make install,return this

**Comment by antoniomtz** [comment]
Same issue here, I can't build the project

**Comment by bogdan-ds** [comment]
This was fixed in the pull request:

https://github.com/gluster/restapi/pull/4
