### ISSUE TITLE
glusterrest.py is missing

### ISSUE THREAD

**Issue by MrCirca** [gluster/restapi#5]
Leaving directory '/root/restapi/src'
make[2]: *** No rule to make target 'glusterrest.py', needed by 'install-restapiPYTHON'.  Stop.

**Comment by aravindavk** [comment]
Thanks for reporting issue. With upcoming Gluster 4.0 release, we will have native REST server provided from glusterd2 itself. This project will be discontinued once the Gluster 4.0 is available.
http://github.com/gluster/glusterd2
